directories:
  output: release
  buildResources: build
appId: com.duetto.app
productName: Duetto
afterPack: scripts/afterPack.js
files:
  - filter:
      - dist/**/*
      - electron.js
      - electron.config.js
      - preload.js
      - package.json
win:
  target:
    - nsis
  icon: build/icon.png
mac:
  target:
    - dmg
  icon: build/icon.png
linux:
  target:
    - AppImage
  icon: build/icon.png
  category: Utility
  executableArgs:
    - '--no-sandbox'
electronVersion: 39.2.3
